### ISSUE TITLE
[Broken]

### ISSUE THREAD

**Issue by bladeosen** [zackmark29/yt-dlp#1]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.06.23**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] [viki] Extracting URL: https://www.viki.com/videos/1183563v-falling-into-your-smile-episode-3
[viki] 1183563v: Downloading video JSON
[viki] 1183563v: Downloading video streams JSON
[viki] 1183563v: Checking for another mpd url
[viki] 1183563v: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: en
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1183563v: Downloading 1 format(s): 3+7
[info] Writing video subtitles to: Falling Into Your Smile - Episode 2 [1183563v].en.vtt
[debug] Invoking downloader on "https://api.viki.io/v4/videos/1183563v/auth_subtitles/en.https://api.viki.io/v4/videos/%s/auth_subtitles/%s.%s?app=%s&stream_id=%s?app=100005a&stream_id=106103621"
WARNING: Unable to download subtitle for "en": HTTP Error 400: Bad Request
[download] Falling Into Your Smile - Episode 2 [1183563v].mp4 has already been downloaded
ERROR: 'filepath'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1144, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1180, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1221, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2200, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2738, in process_info
  File "yt_dlp\YoutubeDL.py", line 2878, in post_process
  File "yt_dlp\YoutubeDL.py", line 2827, in run_pp
  File "yt_dlp\postprocessor\common.py", line 83, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 485, in run
KeyError: 'filepath'

```

## Description

WRITE DESCRIPTION HERE
I can't download the subs, I get on "WARNING: Unable to download subtitle for "en": HTTP Error 400: Bad Request"

**Comment by zackmark29** [comment]
can you show me the command you use

**Comment by bladeosen** [comment]
> 
> 
> can you show me the command you use

Yes.

yt-dlp.exe --verbose --embed-subs --write-auto-sub https://www.viki.com/videos/1183563v-falling-into-your-smile-episode-3

**Comment by zackmark29** [comment]
let me check

**Comment by zackmark29** [comment]
ok fixed. let me upload the binary

**Comment by zackmark29** [comment]
https://github.com/zackmark29/yt-dlp/releases/tag/2021-09-07
